//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirst.tcpReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tcpReference.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SayHello", ReplyAction="http://tempuri.org/IMyService/SayHelloResponse")]
        string SayHello(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SayHello", ReplyAction="http://tempuri.org/IMyService/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/TodayProgram", ReplyAction="http://tempuri.org/IMyService/TodayProgramResponse")]
        string TodayProgram(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/TodayProgram", ReplyAction="http://tempuri.org/IMyService/TodayProgramResponse")]
        System.Threading.Tasks.Task<string> TodayProgramAsync(string strName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : MVCFirst.tcpReference.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<MVCFirst.tcpReference.IMyService>, MVCFirst.tcpReference.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string strName) {
            return base.Channel.SayHello(strName);
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync(string strName) {
            return base.Channel.SayHelloAsync(strName);
        }
        
        public string TodayProgram(string strName) {
            return base.Channel.TodayProgram(strName);
        }
        
        public System.Threading.Tasks.Task<string> TodayProgramAsync(string strName) {
            return base.Channel.TodayProgramAsync(strName);
        }
    }
}
